### ISSUE TITLE
请问不知道错在什么地方？JSON_RPC_URL：这个地址怎么填？填路由器转发的公网ip？还是？

### ISSUE THREAD

**Issue by wlhwlh0482** [jw-star/aria2bot#7]
/app/bot.py:392: DeprecationWarning: There is no current event loop

  loop = asyncio.get_event_loop()

Task exception was never retrieved

future: <Task finished name='Task-17' coro=<main() done, defined at /app/bot.py:43> exception=Aria2rpcException('Server disconnected')>

Traceback (most recent call last):

  File "/root/.local/lib/python3.10/site-packages/aioaria2/client.py", line 804, in new

    self.client_session = await self._client_session.ws_connect(self.url, **self.kw)

  File "/root/.local/lib/python3.10/site-packages/aiohttp/client.py", line 779, in _ws_connect

    resp = await self.request(

  File "/root/.local/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request

    await resp.start(conn)

  File "/root/.local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 899, in start

    message, payload = await protocol.read()  # type: ignore[union-attr]

  File "/root/.local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read

    await self._waiter

aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/app/bot.py", line 44, in main

    await ar.init()

  File "/app/aria2client.py", line 26, in init

    self.client: Aria2WebsocketClient = await Aria2WebsocketClient.new(self.rpc_url, token=self.rpc_token,

  File "/root/.local/lib/python3.10/site-packages/aioaria2/client.py", line 809, in new

    raise Aria2rpcException(str(err), connection_error=("Cannot connect" in str(err))) from err

aioaria2.exceptions.Aria2rpcException: Aria2rpcException: Server disconnected

**Comment by jw-star** [comment]
docker和 路由器在一台机器人就填写 本地ip, 否则公网ip
